dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.DashboardMainView.as_view(), name='dashboard-home'),
    path('posted-jobs/', views.DashboardPostedJobsView.as_view(), name='posted-jobs'),
    path('update-profile/', views.UpdateProfileView.as_view(), name='update-profile'),
    path('update-profile-image/', views.update_profile_image, name='update-profile-image'),
]

pages/urls.py
from django.urls import path

from .views import HomepageView, AboutView, TermsConditionsView, PrivacyPolicyView, login_success

app_name = 'pages'
urlpatterns = [
    path('', HomepageView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('terms/', TermsConditionsView.as_view(), name='terms'),
    path('privacy/', PrivacyPolicyView.as_view(), name='privacy'),
    path('login-success/', login_success, name='login_success'),
]

timebank/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('contact/', include('contact.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('', include('pages.urls')),
    re_path(r'^tinymce/', include('tinymce.urls')),
    path('__reload__/', include('django_browser_reload.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/_alerts.html
{% if messages %}
    <div class="flex flex-col">
        {% for message in messages %}
{#          TODO: Add in appropriate code for info alerts  #}
            <div class="alert-message {% if message.tags == 'success' %}alert-success{% elif message.tags == 'info' %}alert-info{% elif message.tags == 'error' %}alert-error{% endif %}"
                 x-data="{ show: true }"
                 x-show="show"
                 x-init="setTimeout(() => show = false, 5000)"
                 x-transition.duration.200ms
            >
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    class="stroke-current flex-shrink-0 h-6 w-6"
                    fill="none"
                    viewBox="0 0 24 24"
                >
                    {% if message.tags == 'success' %}
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                    {% elif message.tags == 'info' %}
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                    {% elif message.tags == 'error' %}
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                    {% endif %}
                </svg>
                <span>{{ message }}</span>
            </div>
        {% endfor %}
    </div>
{% endif %}

templates/partials/_dashboard_banner.html
<section class='py-6 bg-gray-100'>
    <div class='container mx-auto px-4 grid grid-cols-4 items-center'>
        <div class='col-span-2 lg:col-span-1'>
            <div>
                <span class='font-bold'>Your Rating</span>
                <a href="#" class='ml-2 font-normal text-sm text-indigo-500 hover:underline hover:text-indigo-700'>
                    VIEW ALL
                </a>
            </div>
            <p class='flex justify-start items-center font-bold text-8xl leading-tight text-lime-500'>
                4.75
            </p>
        </div>
        <div class='col-span-2 lg:col-span-1'>
            <p class='font-bold'>
                Your Coins
                <a href="#" class='ml-2 font-normal text-sm text-indigo-500 hover:underline hover:text-indigo-700'>
                    VIEW ALL
                </a>
            </p>
            <p class='flex justify-start items-center font-bold text-8xl leading-tight text-amber-400'>
                39.5
            </p>
        </div>
        <div class='lg:col-span-2'>
            <p class='mb-3 font-bold'>Alerts &amp; Notifications</p>
            <div class='space-y-4'>
                <p class='pt-4 pl-3 border-t-2 border-t-gray-300'>Lorem ipsum dolor sit amet.</p>
                <p class='pt-4 pl-3 border-t-2 border-t-gray-300'>Lorem ipsum dolor sit amet.</p>
                <p class='pt-4 pl-3 border-t-2 border-t-gray-300'>Lorem ipsum dolor sit amet.</p>
            </div>
        </div>
    </div>
</section>

templates/partials/_dashboard_nav.html
<div class="flex flex-col gap-4">
    <a href="{% url 'dashboard:dashboard-home' %}" class="dash-navlink">Dashboard Home</a>
    <a href="{% url 'dashboard:posted-jobs' %}" class="dash-navlink">Posted Jobs</a>
    <a href="#" class="dash-navlink">Applications</a>
    <a href="#" class="dash-navlink">Messages</a>
</div>

templates/partials/_manage_profile_nav.html
<div class="flex flex-col gap-4">
    <a href="{% url 'dashboard:update-profile' %}" class="dash-navlink">Personal Information</a>
    <a href="#" class="dash-navlink">Manage Skills</a>
    <a href="{% url 'dashboard:update-profile-image' %}" class="dash-navlink">Profile Image</a>
    <a href="{% url 'account_email' %}" class="dash-navlink">Manage Email Addresses</a>
    <a href="{% url 'account_change_password' %}" class="dash-navlink">Change Password</a>
</div>