contact/urls.py
from django.urls import path

from .views import ContactUsView

app_name = 'contacts'
urlpatterns = [
    path('', ContactUsView.as_view(), name='contact-us'),
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.DashboardMainView.as_view(), name='dashboard-home'),
    path('posted-jobs/', views.DashboardPostedJobsView.as_view(), name='posted-jobs'),
    path('update-profile/', views.UpdateProfileView.as_view(), name='update-profile'),
    path('update-profile-image/', views.update_profile_image, name='update-profile-image'),
]

pages/urls.py
from django.urls import path

from .views import HomepageView, AboutView, TermsConditionsView, PrivacyPolicyView, login_success

app_name = 'pages'
urlpatterns = [
    path('', HomepageView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('terms/', TermsConditionsView.as_view(), name='terms'),
    path('privacy/', PrivacyPolicyView.as_view(), name='privacy'),
    path('login-success/', login_success, name='login_success'),
]

timebank/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('contact/', include('contact.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('', include('pages.urls')),
    re_path(r'^tinymce/', include('tinymce.urls')),
    path('__reload__/', include('django_browser_reload.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/account_base.html
{% load static tailwind_tags %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&family=Mulish:wght@400;700&display=swap" rel="stylesheet">
    {% tailwind_preload_css %}
    {% tailwind_css %}
    <title>Sullivan TimeBank{% block title %}{% endblock title %}</title>
</head>
<body>
    <main class="min-h-screen px-4 flex flex-col justify-center items-center gap-3 md:gap-6 bg-zinc-100">
        {% block content %}{% endblock content %}
    </main>
</body>
</html>

templates/base.html
{% load static tailwind_tags %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sullivan TimeBank{% block title %}{% endblock title %}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&family=Mulish:wght@400;700&display=swap" rel="stylesheet">
    {% tailwind_preload_css %}
    {% tailwind_css %}
    <link rel="stylesheet" href="{% static 'css/custom_styles.css' %}">
</head>
<body>
    <div class="bg-white shadow">
        <div class="container mx-auto px-4 sm:px-6 lg:px-8">
            <div class="flex justify-between h-16">
                <div class="flex-shrink-0 flex items-center">
                    <a href="{% url 'pages:home' %}">
                        <img
                            src="{% static 'images/sullivan-logo-color.png' %}"
                            alt="Sullivan Logo"
                            class="w-[250px]"
                        />
                    </a>
                </div>
                <div class="hidden sm:ml-6 sm:flex sm:gap-8 sm:items-center">
                    {# TODO: make sure all navlinks are completed #}
                    {% url 'pages:about' as url_about %}
                    {% url 'contacts:contact-us' as url_contact %}
                    <a
                        href="{% url 'pages:about' %}"
                        class="{% if request.path == url_about %}active-navlink{% else %}navlink{% endif %}"
                    >
                        About
                    </a>
                    <a href="#" class="navlink">Jobs</a>
                    <a
                        href="{% url 'contacts:contact-us' %}"
                        class="{% if request.path == url_contact %}active-navlink{% else %}navlink{% endif %}"
                    >
                        Contact Us
                    </a>
                    {% if user.is_authenticated %}
                        <div class="pl-6 border-l-2 dropdown dropdown-end">
                            <div class="flex items-center gap-2">
                                <p class="text-gray-500 font-bold">Hello, {% if user.first_name %}{{ user.first_name }}{% else %}{{ user.username }}{% endif %}!</p>
                                <label tabindex="0" class="btn btn-ghost btn-circle avatar">
                                    <div class="w-10 rounded-full">
                                        <img src="{{ user.current_profile_image }}" />
                                    </div>
                                </label>
                            </div>
                            <ul tabindex="0" class="mt-3 p-2 shadow menu menu-compact dropdown-content z-[1] bg-base-100 rounded-box w-52">
{#                                <li>#}
{#                                    <a class="justify-between">#}
{#                                        Profile#}
{#                                        <span class="badge">New</span>#}
{#                                    </a>#}
{#                                </li>#}
{#                                <li><a>Settings</a></li>#}
                                <li>
                                    <a href="{% url 'dashboard:dashboard-home' %}">Dashboard</a>
                                </li>
                                <li>
                                    <a href="{% url 'dashboard:update-profile' %}">Profile</a>
                                </li>
                                <li>
                                    <a href="{% url 'account_logout' %}">Logout</a>
                                </li>
                            </ul>
                        </div>
                    {% else %}
                        <a href="{% url 'account_login' %}" class="navlink">Login</a>
                        <a href="{% url 'account_signup' %}" class="btn btn-outline btn-primary">
                            Sign Up
                        </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <main class="flex-grow">
        {% block content %}{% endblock content %}
    </main>
    <div class="w-full py-8 bg-gray-700">
        <div class="container mx-auto flex justify-between items-center">
            <img src="{% static 'images/sullivan-logo.png' %}" alt="Sullivan Logo" width="300" />
            <div class="flex gap-8">
                <p class="text-white">&copy;2023 Sullivan Foundation</p>
                <a href="{% url 'pages:terms' %}" class="text-white hover:text-orange-300 duration-150">Terms of Service</a>
                <a href="{% url 'pages:privacy' %}" class="text-white hover:text-orange-300 duration-150">Privacy Policy</a>
            </div>
        </div>
    </div>
<script src="https://kit.fontawesome.com/bcdd1ea5a6.js" crossorigin="anonymous"></script>
<script src="{% static 'js/htmx1-9-5.min.js' %}"></script>
<script src="{% static 'js/alpine-3-13-0.min.js' %}"></script>
{% block extra_body %}{% endblock extra_body %}
</body>
</html>

templates/dashboard_base.html
{% extends 'base.html' %}

{% block content %}
    {% include 'partials/_dashboard_banner.html' %}
    <div class="container mx-auto">
        {% include 'partials/_alerts.html' %}
    </div>
    <div class="container mx-auto mt-8 flex gap-16">
        {% include 'partials/_dashboard_nav.html' %}
        <section>
            {% block dash_content %}{% endblock dash_content %}
        </section>
    </div>
{% endblock content %}

templates/manage_profile_base.html
{% extends 'base.html' %}

{% block content %}
    <div class="py-8 bg-gray-100">
        <div class="container mx-auto">
            <h3>Manage Your Profile</h3>
        </div>
    </div>
    <div class="container mx-auto">
        {% include 'partials/_alerts.html' %}
        {% if not user.is_approved %}
            <div class="mx-auto mt-10">
                <h2 class="mb-4 text-4xl text-gray-700">Hi, {{ user.first_name }}!</h2>
                <h4 class="text-xl text-gray-500">Just one more step to finish your registration.</h4>
                <div class="w-full my-14 p-8 flex flex-col items-center gap-4 border-2 border-orange-500 rounded-2xl
                            lg:flex-row lg:justify-center lg:gap-24"
                >
                    <div class="">
                        <div class="flex items-center gap-3">
                        <span class="text-gray-500">
                            <i class="fa-regular fa-lightbulb fa-4x"></i>
                        </span>
                            <h4 class="text-xl text-gray-500">Tips for creating a strong profile</h4>
                        </div>
                    </div>
                    <ul class="list-disc grow-[2] space-y-3">
                        <li class="text-gray-700">
                            Make sure to use a profile picture that shows your whole face and does not include other people.
                        </li>
                        <li class="text-gray-700">
                            Only list the skills that you know you can provide.
                        </li>
                        <li class="text-gray-700">
                            Add a short, clean additional description if you need.
                        </li>
                    </ul>
                </div>
            </div>
        {% endif %}
        <div class="w-full mb-6 pb-6 flex flex-row">
            <div class="pt-6 pr-10 flex-none basis-1/4">
                <div>
                    {% include 'partials/_manage_profile_nav.html' %}
                </div>
            </div>
            <div class="basis-3/4 flex-none">
                {% block profile_content %}{% endblock profile_content %}
            </div>
        </div>
    </div>
{% endblock content %}